workspace "dx12_renderer"
	configurations { "Debug", "Release" }
	system "Windows"
    architecture "x86_64"
	language "C++"
	cppdialect "C++20"
	location "build"
	startproject "demoApp"
	staticruntime "on"
	flags "MultiProcessorCompile"

filter "Debug"
	runtime "Debug"
	symbols "on"
	optimize "off"
	targetdir "build/bin/debug"
	debugdir "build/bin/debug"
	defines "_DEBUG"

filter "Release"
	runtime "Release"
	symbols "off"
	optimize "on"
	targetdir "build/bin/release"
	debugdir "build/bin/release"
	flags "LinkTimeOptimization"

include "dx12_renderer"
include "demoApp"