workspace "dx12_renderer"
	configurations { "Debug", "DebugASAN", "Release" }
	system "Windows"
    architecture "x86_64"
	language "C++"
	cppdialect "C++20"
	location "build"
	startproject "demoApp"
	staticruntime "on"
	flags "MultiProcessorCompile"

filter "Debug"
	runtime "Debug"
	symbols "on"
	optimize "off"
	targetdir "build/bin/debug"
	debugdir "build/bin/debug"
	defines "RENDERER_DEBUG"

filter "DebugASAN"
	runtime "Debug"
	symbols "default"
	optimize "off"
	targetdir "build/bin/debug"
	debugdir "build/bin/debug"
	defines "RENDERER_DEBUG"
	sanitize "Address"

filter "Release"
	runtime "Release"
	symbols "off"
	optimize "on"
	targetdir "build/bin/release"
	debugdir "build/bin/release"
	linktimeoptimization "on"

include "dx12_renderer"
include "demoApp"