#include "PixelShader.h"

#include <d3dx12.h>
#include <dxcapi.h>

#include <regex>

#include <Renderer.h>

PixelShader::PixelShader( std::string filename )
{
    // 
    // Create compiler and utils.
    //
    ComPtr<IDxcUtils> pUtils;
    ComPtr<IDxcCompiler3> pCompiler;
    DxcCreateInstance(CLSID_DxcUtils, IID_PPV_ARGS(&pUtils));
    DxcCreateInstance(CLSID_DxcCompiler, IID_PPV_ARGS(&pCompiler));

    //
    // Create default include handler. (You can create your own...)
    //
    ComPtr<IDxcIncludeHandler> pIncludeHandler;
    pUtils->CreateDefaultIncludeHandler(&pIncludeHandler);


    std::wstring filenameWideStr = std::wstring(filename.begin(), filename.end());

    std::string csoFilename = std::regex_replace(filename, std::regex("hlsl"), "cso");
    std::wstring csoFilenameWideStr = std::wstring(csoFilename.begin(), csoFilename.end());

    std::string pdbFilename = std::regex_replace(filename, std::regex("hlsl"), "pdb");
    std::wstring pdbFilenameWideStr = std::wstring(pdbFilename.begin(), pdbFilename.end());

    LPCWSTR pszArgs[] =
    {
        filenameWideStr.c_str(),               // Optional shader source file name for error reporting and for PIX shader source view.  
        L"-E", L"main_ps",              // Entry point.
        L"-T", L"ps_6_0",            // Target.
        L"-Zs",                      // Enable debug information (slim format)
        L"-D", L"MYDEFINE=1",        // A single define.
        L"-Fo", csoFilenameWideStr.c_str(),     // Optional. Stored in the pdb. 
        L"-Fd", pdbFilenameWideStr.c_str(),     // The file name of the pdb. This must either be supplied or the autogenerated file name must be used.
    };


    //
    // Open source file.  
    //
    ComPtr<IDxcBlobEncoding> pSource = nullptr;
    pUtils->LoadFile(filenameWideStr.c_str(), nullptr, &pSource);
    DxcBuffer Source;
    Source.Ptr = pSource->GetBufferPointer();
    Source.Size = pSource->GetBufferSize();
    Source.Encoding = DXC_CP_ACP; // Assume BOM says UTF8 or UTF16 or this is ANSI text.


    //
    // Compile it with specified arguments.
    //
    ComPtr<IDxcResult> pResults;
    pCompiler->Compile(
        &Source,                // Source buffer.
        pszArgs,                // Array of pointers to arguments.
        _countof(pszArgs),      // Number of arguments.
        pIncludeHandler.Get(),  // User-provided interface to handle #include directives (optional).
        IID_PPV_ARGS(&pResults) // Compiler output status, buffer, and errors.
    );
    pResults->GetOutput(DXC_OUT_OBJECT, IID_PPV_ARGS(&m_bytecode), nullptr);

    //
    // Save pdb.
    //
    ComPtr<IDxcBlob> pPDB = nullptr;
    ComPtr<IDxcBlobUtf16> pPDBName = nullptr;
    pResults->GetOutput(DXC_OUT_PDB, IID_PPV_ARGS(&pPDB), &pPDBName);
    if (pPDB && pPDBName)
    {
        FILE* fp = NULL;

        // Note that if you don't specify -Fd, a pdb name will be automatically generated. Use this file name to save the pdb so that PIX can find it quickly.
        _wfopen_s(&fp, pPDBName->GetStringPointer(), L"wb");
        if (fp)
        {
            fwrite(pPDB->GetBufferPointer(), pPDB->GetBufferSize(), 1, fp);
            fclose(fp);
        }
    }
}

PixelShader::~PixelShader()
{

}

void PixelShader::bind( Renderer::RenderContext& context )
{
	context.m_pipelineState.m_pixelShader = CD3DX12_SHADER_BYTECODE(m_bytecode->GetBufferPointer(), m_bytecode->GetBufferSize());
}
